import { LiveChannel } from './types';

// Edit this list to control the Live TV guide in /live.
export const LIVE_CHANNELS: LiveChannel[] = [
  {
    id: 'lofi-live',
    name: 'Lofi Girl Live',
    provider: 'youtube',
    embedType: 'live',
    videoId: 'jfKfPfyJRdk',
    thumbnail: 'https://i.ytimg.com/vi/jfKfPfyJRdk/hqdefault.jpg',
    description: '24/7 lo-fi stream for focus and background listening.',
    category: 'Music',
    language: 'en',
    tags: ['music', 'focus', 'ambient'],
    featured: true,
  },
  {
    id: 'nasa-live',
    name: 'NASA Live',
    provider: 'youtube',
    embedType: 'live',
    videoId: '21X5lGlDOfg',
    thumbnail: 'https://i.ytimg.com/vi/21X5lGlDOfg/hqdefault.jpg',
    description: 'Space-focused live stream from NASA.',
    category: 'Science',
    language: 'en',
    tags: ['space', 'science', 'education'],
  },
  {
    id: 'finchwire-news-playlist',
    name: 'FinchWire News Mix (Sample)',
    provider: 'youtube',
    embedType: 'playlist',
    playlistId: 'PLFgquLnL59alCl_2TQvOiD5Vgm1hCaGSI',
    thumbnail: 'https://i.ytimg.com/vi/6Dh-RL__uN4/hqdefault.jpg',
    description: 'Sample playlist slot for your own curated news/video feed.',
    category: 'News',
    language: 'en',
    tags: ['news', 'playlist', 'curated'],
  },
  {
    id: 'sky-news-live',
    name: 'Sky News Live',
    provider: 'youtube',
    embedType: 'live',
    videoId: '9Auq9mYxFEE',
    thumbnail: 'https://i.ytimg.com/vi/9Auq9mYxFEE/hqdefault.jpg',
    description: 'Live news stream for world events.',
    category: 'News',
    language: 'en',
    tags: ['breaking', 'world', 'news'],
  },
];
