import { LiveChannel } from './types';

// Edit this list to control the Live TV guide in /live.
export const LIVE_CHANNELS: LiveChannel[] = [
  {
    id: 'abc-news-live',
    name: 'ABC News Live',
    provider: 'hls',
    embedType: 'live',
    streamUrl: 'https://content.uplynk.com/channel/332e87901da44e0591e0a8b9264cae5d.m3u8',
    thumbnail: 'https://i.abcnewsfe.com/a/36a7ed2c-232e-4b7b-8919-6330058e3713/abc_news_live_logo_v01_16x9_992.jpg',
    description: '24/7 breaking news and analysis from ABC News.',
    category: 'News',
    language: 'en',
    tags: ['news', 'live', 'breaking'],
    featured: true,
  },
  {
    id: 'cbs-news-live',
    name: 'CBS News',
    provider: 'hls',
    embedType: 'live',
    streamUrl: 'https://cbsn-us.akamaized.net/hls/live/2020648/cbsn_us/master.m3u8',
    thumbnail: 'https://www.cbsnews.com/flywheel/v2/img/cbsnews-video-player-poster.jpg',
    description: 'CBS News 24/7 is the premier free live news network.',
    category: 'News',
    language: 'en',
    tags: ['news', 'live', 'cbs'],
    featured: true,
  },
  {
    id: 'sky-news-live',
    name: 'Sky News',
    provider: 'youtube',
    embedType: 'live',
    videoId: 'YDvsBbKfLPA',
    thumbnail: 'https://yt3.googleusercontent.com/ytc/AIdro_n9G9H9_9n9G9H9_9n9G9H9_9n9G9H9_9n9G9H9=s900-c-k-c0x00ffffff-no-rj',
    description: 'World-class news coverage from Sky News.',
    category: 'News',
    language: 'en',
    tags: ['news', 'live', 'sky'],
  },
  {
    id: 'nasa-tv',
    name: 'NASA TV',
    provider: 'youtube',
    embedType: 'live',
    videoId: 'zPH5KtjJFaQ',
    thumbnail: 'https://www.nasa.gov/wp-content/themes/nasa/assets/images/nasa-logo.svg',
    description: 'NASA Television provides live coverage of launches, spacewalks, and other mission events.',
    category: 'Science',
    language: 'en',
    tags: ['space', 'science', 'documentary'],
  },
  {
    id: 'weathernational-live',
    name: 'WeatherNation',
    provider: 'hls',
    embedType: 'live',
    streamUrl: 'https://weathernation.allente.stream/hls/live/master.m3u8',
    thumbnail: 'https://www.weathernationtv.com/wp-content/uploads/2016/04/WNTV_Logo_Stacked_RGB.jpg',
    description: '24/7 live weather coverage and tracking.',
    category: 'Weather',
    language: 'en',
    tags: ['weather', 'live', 'tracking'],
  },
  {
    id: 'bloomberg-live',
    name: 'Bloomberg TV',
    provider: 'youtube',
    embedType: 'live',
    videoId: 'iEpJwprxDdk',
    thumbnail: 'https://yt3.googleusercontent.com/ytc/AIdro_k6y6G8-p8P5-p8P5-p8P5-p8P5-p8P5-p8P5-p8P5=s900-c-k-c0x00ffffff-no-rj',
    description: '24-hour global business and financial news.',
    category: 'News',
    language: 'en',
    tags: ['news', 'business', 'finance'],
  },
  {
    id: 'lofi-live',
    name: 'Lofi Girl Live',
    provider: 'youtube',
    embedType: 'live',
    videoId: 'jfKfPfyJRdk',
    thumbnail: 'https://i.ytimg.com/vi/jfW77iZ6F7Q/hqdefault.jpg',
    description: '24/7 lo-fi stream for focus and background listening.',
    category: 'Music',
    language: 'en',
    tags: ['music', 'focus', 'ambient'],
  },
];
